ALTER TABLE guide_blocks ADD COLUMN block_category VARCHAR(30) NOT NULL DEFAULT 'ACTIVITY'
    CHECK (block_category IN ('ACTIVITY', 'SAFETY', 'TRANSPORT', 'ACCOMMODATION', 'SHOPPING', 'SEASONAL', 'EMERGENCY', 'SECRET'));
